name: Execução de testes

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'

      - name: Permission for linux
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./gradlew.bat build
          else
            ./gradlew build
          fi

      - name: Tests
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./gradlew.bat test
          else
            ./gradlew test
          fi

      - name: JaCoCo report
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./gradlew.bat jacocoTestReport
          else
            ./gradlew jacocoTestReport
          fi

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html/